# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: J. S. Cooper - A Curious Mathematician
email: jsc42@cantab.net
description: > # this means to ignore newlines until "baseurl:"
  A place for me to reflect on my experiences of mathematical research, education, coding, 
  and the search for a engaging career.

baseurl: "/website/" # the subpath of your site, e.g. /blog
url: "http://jamesthetab.github.io" # the base hostname & protocol for your site
github_username:  jamesthetab

# Build settings
markdown: kramdown
